### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by trevatk** [structx/raft#1]
- [ ] add unit tests
- [ ] include examples dir
- [ ] convert to lib
- [ ] add kv store
